### ISSUE TITLE
Error 403 - forbidden

### ISSUE THREAD

**Issue by DaniellMesquita** [0xProject/0x-launch-kit#26]
First, it said docker wasn't detected as running. Using it with sudo had fixed it, but yet not exporting the frontend. After manually creating /usr/share/nginx/html and putting user-group docker with RW permissions, docker-composer can now run without sudo. But it yet isn't exporting to /nginx/html.

**Comment by DaniellMesquita** [comment]
In `0x-launch-kit`, did that:
```bash
cd /1/Apps/0x-launch-kit && docker-compose stop && docker-compose up
```

Which produced:

> Starting 0x-launch-kit_frontend_1 ... done
> Starting 0x-launch-kit_backend_1  ... done
> Starting 0x-launch-kit_nginx_1    ... done
> Attaching to 0x-launch-kit_frontend_1, 0x-launch-kit_backend_1, 0x-launch-kit_nginx_1
> frontend_1  | yarn run v1.15.2
> frontend_1  | $ react-scripts build
> backend_1   | warn:    --minUptime not set. Defaulting to: 1000ms
> backend_1   | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> frontend_1  | Creating an optimized production build...
> backend_1   | query: BEGIN TRANSACTION
> backend_1   | query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('signed_order_model', 'signed_order_model')
> backend_1   | query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('signed_order_model', 'signed_order_model')
> backend_1   | query: PRAGMA table_info("signed_order_model")
> backend_1   | query: PRAGMA index_list("signed_order_model")
> backend_1   | query: PRAGMA foreign_key_list("signed_order_model")
> backend_1   | query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
> backend_1   | query: COMMIT
> backend_1   | WARNING: Multiple definitions for safeTransferFrom
> backend_1   | WARNING: Multiple definitions for safeTransferFrom
> backend_1   | WARNING: Multiple definitions for safeTransferFrom
> backend_1   | query: SELECT "SignedOrderModel"."hash" AS "SignedOrderModel_hash", "SignedOrderModel"."senderAddress" AS "SignedOrderModel_senderAddress", "SignedOrderModel"."makerAddress" AS "SignedOrderModel_makerAddress", "SignedOrderModel"."takerAddress" AS "SignedOrderModel_takerAddress", "SignedOrderModel"."makerAssetData" AS "SignedOrderModel_makerAssetData", "SignedOrderModel"."takerAssetData" AS "SignedOrderModel_takerAssetData", "SignedOrderModel"."exchangeAddress" AS "SignedOrderModel_exchangeAddress", "SignedOrderModel"."feeRecipientAddress" AS "SignedOrderModel_feeRecipientAddress", "SignedOrderModel"."expirationTimeSeconds" AS "SignedOrderModel_expirationTimeSeconds", "SignedOrderModel"."makerFee" AS "SignedOrderModel_makerFee", "SignedOrderModel"."takerFee" AS "SignedOrderModel_takerFee", "SignedOrderModel"."makerAssetAmount" AS "SignedOrderModel_makerAssetAmount", "SignedOrderModel"."takerAssetAmount" AS "SignedOrderModel_takerAssetAmount", "SignedOrderModel"."salt" AS "SignedOrderModel_salt", "SignedOrderModel"."signature" AS "SignedOrderModel_signature" FROM "signed_order_model" "SignedOrderModel"
> backend_1   | Standard relayer API (HTTP) listening on port 3000!
> backend_1   | Config: {
> backend_1   |   "WHITELISTED_TOKENS": "*",
> backend_1   |   "HTTP_PORT": 3000,
> backend_1   |   "NETWORK_ID": 1,
> backend_1   |   "FEE_RECIPIENT": "0x3ea9e702AA552B19e36346eb40116DB0fd16BE35",
> backend_1   |   "MAKER_FEE_ZRX_UNIT_AMOUNT": "0.1",
> backend_1   |   "TAKER_FEE_ZRX_UNIT_AMOUNT": "0.05",
> backend_1   |   "RPC_URL": "https://mainnet.infura.io/",
> backend_1   |   "DEFAULT_TAKER_SIMULATION_ADDRESS": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
> backend_1   |   "ORDER_SHADOWING_MARGIN_MS": 100000,
> backend_1   |   "PERMANENT_CLEANUP_INTERVAL_MS": 10000,
> backend_1   |   "MAX_PER_PAGE": 1000,
> backend_1   |   "DEFAULT_ERC20_TOKEN_PRECISION": 18
> backend_1   | }
> frontend_1  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> frontend_1  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> frontend_1  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> frontend_1  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> frontend_1  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
> frontend_1  | Compiled successfully.
> frontend_1  | 
> frontend_1  | File sizes after gzip:
> frontend_1  | 
> frontend_1  |   799.45 KB  build/static/js/2.e003944c.chunk.js
> frontend_1  |   175.55 KB  build/static/js/main.f2d6c473.chunk.js
> frontend_1  |   1.28 KB    build/static/css/2.306bd6cf.chunk.css
> frontend_1  |   762 B      build/static/js/runtime~main.a8a9905a.js
> frontend_1  |   249 B      build/static/css/main.fbadd610.chunk.css
> frontend_1  | 
> frontend_1  | The project was built assuming it is hosted at the server root.
> frontend_1  | You can control this with the homepage field in your package.json.
> frontend_1  | For example, add this to build it for GitHub Pages:
> frontend_1  | 
> frontend_1  |   "homepage" : "http://myname.github.io/myapp",
> frontend_1  | 
> frontend_1  | The build folder is ready to be deployed.
> frontend_1  | You may serve it with a static server:
> frontend_1  | 
> frontend_1  |   yarn global add serve
> frontend_1  |   serve -s build
> frontend_1  | 
> frontend_1  | Find out more about deployment here:
> frontend_1  | 
> frontend_1  |   https://bit.ly/CRA-deploy
> frontend_1  | 
> frontend_1  | Done in 542.41s.
> 0x-launch-kit_frontend_1 exited with code 0
> backend_1   | { [InternalError: network timeout at: https://mainnet.infura.io/]
> backend_1   |   message: 'network timeout at: https://mainnet.infura.io/',
> backend_1   |   code: -32603 }
> backend_1   | { [InternalError: network timeout at: https://mainnet.infura.io/]
> backend_1   |   message: 'network timeout at: https://mainnet.infura.io/',
> backend_1   |   code: -32603 }
> backend_1   | (node:17) UnhandledPromiseRejectionWarning: FetchError: response timeout at https://mainnet.infura.io/ over limit: 20000
> backend_1   |     at Timeout._onTimeout (/usr/src/app/node_modules/node-fetch/lib/body.js:117:12)
> backend_1   |     at listOnTimeout (internal/timers.js:535:17)
> backend_1   |     at processTimers (internal/timers.js:479:7)
> backend_1   | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> backend_1   | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> backend_1   | (node:17) UnhandledPromiseRejectionWarning: FetchError: response timeout at https://mainnet.infura.io/ over limit: 20000
> backend_1   |     at Timeout._onTimeout (/usr/src/app/node_modules/node-fetch/lib/body.js:117:12)
> backend_1   |     at listOnTimeout (internal/timers.js:535:17)
> backend_1   |     at processTimers (internal/timers.js:479:7)
> backend_1   | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> 0x-launch-kit_nginx_1 exited with code 0
> 0x-launch-kit_backend_1 exited with code 137
> 

It seems like the backnd is rejecting node_fetch, preventing it to use Infura API.

**Comment by DaniellMesquita** [comment]
Instead of using `docker-compose`, I'd just used `docker`.

Following cmd I'd used:
`docker-ps`:

> floflis@floflis-C14RV01:~$ docker ps
> CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
> a2c859795a1b        0xorg/launch-kit-backend    "docker-entrypoint.s…"   2 days ago          Up 4 minutes        0.0.0.0:3000->3000/tcp   0x-launch-kit_backend_1
> 520e1947fc80        nginx                       "nginx -g 'daemon of…"   2 days ago          Up 4 minutes        0.0.0.0:3001->80/tcp     0x-launch-kit_nginx_1
> df8ad751c0a8        0xorg/launch-kit-frontend   "docker-entrypoint.s…"   2 days ago          Up 4 minutes                                 0x-launch-kit_frontend_1

`docker info`:

> floflis@floflis-C14RV01:~$ docker info
> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 3
>   Running: 3
>   Paused: 0
>   Stopped: 0
>  Images: 3
>  Server Version: 19.03.2
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 5.0.0-13-generic
>  Operating System: Floflis 0 build 051
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 2
>  Total Memory: 3.323GiB
>  Name: floflis-C14RV01
>  ID: VFSC:ASOA:DXCB:WQMI:A2TL:FV2I:HJXJ:IS5M:XQQN:TWLG:JV4L:OTAC
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No swap limit support
> 

The most interesting: even `docker ps` showing all three containers are running, trying the `top` arg in frontend container said it isn't running:

> floflis@floflis-C14RV01:~$ docker container top df8ad751c0a8
> Error response from daemon: Container df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d is not running
> 

Then, started it:

> floflis@floflis-C14RV01:~$ docker container start df8ad751c0a8
> df8ad751c0a8
>

**Comment by DaniellMesquita** [comment]
Inspected the frontnd container:

> floflis@floflis-C14RV01:~$ docker container inspect df8ad751c0a8
> [
>     {
>         "Id": "df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d",
>         "Created": "2019-10-01T16:40:40.459910465Z",
>         "Path": "docker-entrypoint.sh",
>         "Args": [
>             "yarn",
>             "build"
>         ],
>         "State": {
>             "Status": "running",
>             "Running": true,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 5045,
>             "ExitCode": 0,
>             "Error": "",
>             "StartedAt": "2019-10-04T01:56:50.087847971Z",
>             "FinishedAt": "2019-10-04T01:51:44.94124235Z"
>         },
>         "Image": "sha256:6c344b4e74f8384a6224e985eba3e3583cab66b4d8cf54ba6b4287836a69669f",
>         "ResolvConfPath": "/var/lib/docker/containers/df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d/resolv.conf",
>         "HostnamePath": "/var/lib/docker/containers/df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d/hostname",
>         "HostsPath": "/var/lib/docker/containers/df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d/hosts",
>         "LogPath": "/var/lib/docker/containers/df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d/df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d-json.log",
>         "Name": "/0x-launch-kit_frontend_1",
>         "RestartCount": 0,
>         "Driver": "overlay2",
>         "Platform": "linux",
>         "MountLabel": "",
>         "ProcessLabel": "",
>         "AppArmorProfile": "docker-default",
>         "ExecIDs": null,
>         "HostConfig": {
>             "Binds": [
>                 "0x-launch-kit_frontend-assets:/app/build:rw"
>             ],
>             "ContainerIDFile": "",
>             "LogConfig": {
>                 "Type": "json-file",
>                 "Config": {}
>             },
>             "NetworkMode": "0x-launch-kit_default",
>             "PortBindings": {},
>             "RestartPolicy": {
>                 "Name": "",
>                 "MaximumRetryCount": 0
>             },
>             "AutoRemove": false,
>             "VolumeDriver": "",
>             "VolumesFrom": [],
>             "CapAdd": null,
>             "CapDrop": null,
>             "Capabilities": null,
>             "Dns": [],
>             "DnsOptions": [],
>             "DnsSearch": [],
>             "ExtraHosts": null,
>             "GroupAdd": null,
>             "IpcMode": "shareable",
>             "Cgroup": "",
>             "Links": null,
>             "OomScoreAdj": 0,
>             "PidMode": "",
>             "Privileged": false,
>             "PublishAllPorts": false,
>             "ReadonlyRootfs": false,
>             "SecurityOpt": null,
>             "UTSMode": "",
>             "UsernsMode": "",
>             "ShmSize": 67108864,
>             "Runtime": "runc",
>             "ConsoleSize": [
>                 0,
>                 0
>             ],
>             "Isolation": "",
>             "CpuShares": 0,
>             "Memory": 0,
>             "NanoCpus": 0,
>             "CgroupParent": "",
>             "BlkioWeight": 0,
>             "BlkioWeightDevice": null,
>             "BlkioDeviceReadBps": null,
>             "BlkioDeviceWriteBps": null,
>             "BlkioDeviceReadIOps": null,
>             "BlkioDeviceWriteIOps": null,
>             "CpuPeriod": 0,
>             "CpuQuota": 0,
>             "CpuRealtimePeriod": 0,
>             "CpuRealtimeRuntime": 0,
>             "CpusetCpus": "",
>             "CpusetMems": "",
>             "Devices": null,
>             "DeviceCgroupRules": null,
>             "DeviceRequests": null,
>             "KernelMemory": 0,
>             "KernelMemoryTCP": 0,
>             "MemoryReservation": 0,
>             "MemorySwap": 0,
>             "MemorySwappiness": null,
>             "OomKillDisable": false,
>             "PidsLimit": null,
>             "Ulimits": null,
>             "CpuCount": 0,
>             "CpuPercent": 0,
>             "IOMaximumIOps": 0,
>             "IOMaximumBandwidth": 0,
>             "MaskedPaths": [
>                 "/proc/asound",
>                 "/proc/acpi",
>                 "/proc/kcore",
>                 "/proc/keys",
>                 "/proc/latency_stats",
>                 "/proc/timer_list",
>                 "/proc/timer_stats",
>                 "/proc/sched_debug",
>                 "/proc/scsi",
>                 "/sys/firmware"
>             ],
>             "ReadonlyPaths": [
>                 "/proc/bus",
>                 "/proc/fs",
>                 "/proc/irq",
>                 "/proc/sys",
>                 "/proc/sysrq-trigger"
>             ]
>         },
>         "GraphDriver": {
>             "Data": {
>                 "LowerDir": "/var/lib/docker/overlay2/be4eab9764000c0cede0d920e567c36c6cc8ea173534a4a06d0196ce7bed421b-init/diff:/var/lib/docker/overlay2/70aa071849942f954dd9a6275194d2dc837294817667f1e5cc1d7f5fd7ecb1a3/diff:/var/lib/docker/overlay2/229bf2189a568f899640379b9119b5c72307df524e70c28c4c14b0fcaea65fa7/diff:/var/lib/docker/overlay2/27594584b7afc69170e733146646bac92524a1e575fff3ac2d481945bfa39a14/diff:/var/lib/docker/overlay2/b64fbef5485ee48f28cd7a02352b6e65beb0d14525656017034601330677a403/diff:/var/lib/docker/overlay2/6de16813831e4d6908956e656cf7446bd224b213cd7fc77edabc9f782118de74/diff:/var/lib/docker/overlay2/a198511b6089f0eece9a6d4807340a213d4c6615674ba171db95e27aae7e2315/diff:/var/lib/docker/overlay2/28aaff54d895b7d99cb423825ff533c77d7d1bd9e59e65f4c6407de58631acc1/diff:/var/lib/docker/overlay2/d526d2a7606c398ee7065202176b59611b78da9700a003665001b710b2610613/diff",
>                 "MergedDir": "/var/lib/docker/overlay2/be4eab9764000c0cede0d920e567c36c6cc8ea173534a4a06d0196ce7bed421b/merged",
>                 "UpperDir": "/var/lib/docker/overlay2/be4eab9764000c0cede0d920e567c36c6cc8ea173534a4a06d0196ce7bed421b/diff",
>                 "WorkDir": "/var/lib/docker/overlay2/be4eab9764000c0cede0d920e567c36c6cc8ea173534a4a06d0196ce7bed421b/work"
>             },
>             "Name": "overlay2"
>         },
>         "Mounts": [
>             {
>                 "Type": "volume",
>                 "Name": "0x-launch-kit_frontend-assets",
>                 "Source": "/var/lib/docker/volumes/0x-launch-kit_frontend-assets/_data",
>                 "Destination": "/app/build",
>                 "Driver": "local",
>                 "Mode": "rw",
>                 "RW": true,
>                 "Propagation": ""
>             }
>         ],
>         "Config": {
>             "Hostname": "df8ad751c0a8",
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "Tty": false,
>             "OpenStdin": false,
>             "StdinOnce": false,
>             "Env": [
>                 "REACT_APP_RELAYER_URL=http://localhost:3000/v2",
>                 "REACT_APP_DEFAULT_BASE_PATH=/erc20",
>                 "REACT_APP_THEME_NAME=LIGHT_THEME",
>                 "REACT_APP_NETWORK_ID=1",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                 "NODE_VERSION=8.16.0",
>                 "YARN_VERSION=1.15.2"
>             ],
>             "Cmd": [
>                 "yarn",
>                 "build"
>             ],
>             "Image": "0xorg/launch-kit-frontend",
>             "Volumes": {
>                 "/app/build": {}
>             },
>             "WorkingDir": "/app",
>             "Entrypoint": [
>                 "docker-entrypoint.sh"
>             ],
>             "OnBuild": null,
>             "Labels": {
>                 "com.docker.compose.config-hash": "ef7363f2339a3f75bd7edb0a4d4005988ed83e3780a10490e426f07ee78af3af",
>                 "com.docker.compose.container-number": "1",
>                 "com.docker.compose.oneoff": "False",
>                 "com.docker.compose.project": "0x-launch-kit",
>                 "com.docker.compose.service": "frontend",
>                 "com.docker.compose.version": "1.24.1"
>             }
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "f8544483c0582c32f4df3450db4a81b3a15e58e66f40b357487b09807c969b19",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {},
>             "SandboxKey": "/var/run/docker/netns/f8544483c058",
>             "SecondaryIPAddresses": null,
>             "SecondaryIPv6Addresses": null,
>             "EndpointID": "",
>             "Gateway": "",
>             "GlobalIPv6Address": "",
>             "GlobalIPv6PrefixLen": 0,
>             "IPAddress": "",
>             "IPPrefixLen": 0,
>             "IPv6Gateway": "",
>             "MacAddress": "",
>             "Networks": {
>                 "0x-launch-kit_default": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": [
>                         "df8ad751c0a8",
>                         "frontend"
>                     ],
>                     "NetworkID": "a8261ce55bb9263e409bbda1bd6064e63dd5fa466f390bc0140ce67ef5ca03d2",
>                     "EndpointID": "95b7b15b98599d61c5493cd36eabd500a11b42c037baadf3fc42cea63bc2975e",
>                     "Gateway": "172.18.0.1",
>                     "IPAddress": "172.18.0.3",
>                     "IPPrefixLen": 16,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "02:42:ac:12:00:03",
>                     "DriverOpts": null
>                 }
>             }
>         }
>     }
> ]
> 

In this repo, used `docker-compose build` command:

> floflis@floflis-C14RV01:/1/Apps/0x-launch-kit$ docker-compose build
> frontend uses an image, skipping
> backend uses an image, skipping
> nginx uses an image, skipping
> 

Then, instead of using the recommended addresses, used through this: http://127.0.0.1:3001/

![Screenshot from 2019-10-03 22-50-42](https://user-images.githubusercontent.com/6765277/66177659-50354d80-e630-11e9-8afc-189884cb9d6c.png)

It worked, possible because of the `docker container start df8ad751c0a8`

**Comment by DaniellMesquita** [comment]
Why using `docker-compose` instead of just `docker`? Because it is easier? Or not totally relying it, or providing better docs about whether to use just `docker` when `docker-compose` doesn't works.

**Comment by DaniellMesquita** [comment]
Probably because of a node module, it isn't connecting to Infura and isn't getting the values of tokens:

![Screenshot from 2019-10-03 23-00-00](https://user-images.githubusercontent.com/6765277/66177962-90490000-e631-11e9-82a5-5e0deab62fd5.png)

> backend_1 | { [InternalError: network timeout at: https://mainnet.infura.io/]
> backend_1 | message: 'network timeout at: https://mainnet.infura.io/',
> backend_1 | code: -32603 }
> backend_1 | { [InternalError: network timeout at: https://mainnet.infura.io/]
> backend_1 | message: 'network timeout at: https://mainnet.infura.io/',
> backend_1 | code: -32603 }
> backend_1 | (node:17) UnhandledPromiseRejectionWarning: FetchError: response timeout at https://mainnet.infura.io/ over limit: 20000
> backend_1 | at Timeout._onTimeout (/usr/src/app/node_modules/node-fetch/lib/body.js:117:12)
> backend_1 | at listOnTimeout (internal/timers.js:535:17)
> backend_1 | at processTimers (internal/timers.js:479:7)
> backend_1 | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> backend_1 | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> backend_1 | (node:17) UnhandledPromiseRejectionWarning: FetchError: response timeout at https://mainnet.infura.io/ over limit: 20000
> backend_1 | at Timeout._onTimeout (/usr/src/app/node_modules/node-fetch/lib/body.js:117:12)
> backend_1 | at listOnTimeout (internal/timers.js:535:17)
> backend_1 | at processTimers (internal/timers.js:479:7)
> backend_1 | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by DaniellMesquita** [comment]
Also, how to edit its JSON config and re-deploy it?

**Comment by DaniellMesquita** [comment]
Its weird how it isn't using light theme as in its settings:
`"REACT_APP_THEME_NAME=LIGHT_THEME",`
https://github.com/0xProject/0x-launch-kit/issues/26#issuecomment-538206687

**Comment by DaniellMesquita** [comment]
@tomhschmidt @dekz

**Comment by DaniellMesquita** [comment]
Weirder how, after using docker `container start df8ad751c0a8`, it doesn't anymore shows up when using `ps`:

![Screenshot from 2019-10-03 23-58-51](https://user-images.githubusercontent.com/6765277/66180264-529ca500-e63a-11e9-9768-48fb10fa205c.png)

**Comment by DaniellMesquita** [comment]
> floflis@floflis-C14RV01:~$ docker container exec df8ad751c0a8 ls
> Error response from daemon: Container df8ad751c0a85784db12abc760a32e37e3012dfa64bce26ba30df2f96c7d444d is not running

But the UI site is yet working.

**Comment by dekz** [comment]
The `frontend` container is a "build" container which creates the bundle and injects into the `nginx` container. From then on, `nginx` serves up the optimised bundle.

```
backend_1 | "RPC_URL": "https://mainnet.infura.io/",
```
If you're using INFURA you need a projectId, you cannot use just `https://mainnet.infura.io/` anymore.

**Comment by DaniellMesquita** [comment]
@dekz
> If you're using INFURA you need a projectId, you cannot use just https://mainnet.infura.io/ anymore.

I didn't read here about that in docs.
How to set the projectId for the API?

**Comment by dekz** [comment]
It is set in the Launch Kit Wizard or you can change it in the docker
compose. You provide the full RPC url that you find in the INFURA
dashboard.
